{
  "uid" : "f23dfe9af76c2138",
  "name" : "test_xfail_unexpected_pass",
  "fullName" : "allure_pytest.test_xfail_unexpected_pass",
  "historyId" : "b548d343298f402ba22d889385257c19",
  "time" : {
    "start" : 1537969909205,
    "stop" : 1537969909206,
    "duration" : 1
  },
  "description" : "this test is an xfail that will be marked as unexpected success",
  "descriptionHtml" : "<p>this test is an xfail that will be marked as unexpected success</p>\n",
  "status" : "passed",
  "flaky" : false,
  "beforeStages" : [ ],
  "afterStages" : [ ],
  "labels" : [ {
    "name" : "framework",
    "value" : "pytest"
  }, {
    "name" : "host",
    "value" : "Dudnikov"
  }, {
    "name" : "language",
    "value" : "cpython3"
  }, {
    "name" : "severity",
    "value" : "normal"
  }, {
    "name" : "thread",
    "value" : "988-MainThread"
  }, {
    "name" : "suite",
    "value" : "allure_pytest"
  }, {
    "name" : "testClass",
    "value" : "allure_pytest"
  }, {
    "name" : "testMethod",
    "value" : "test_xfail_unexpected_pass"
  }, {
    "name" : "package",
    "value" : "allure_pytest"
  }, {
    "name" : "resultFormat",
    "value" : "allure1"
  } ],
  "parameters" : [ ],
  "links" : [ ],
  "hidden" : false,
  "retry" : false,
  "extra" : {
    "severity" : "normal",
    "retries" : [ ],
    "categories" : [ ],
    "tags" : [ ]
  },
  "source" : "f23dfe9af76c2138.json",
  "parameterValues" : [ ]
}